---
name: mender-createuser
include:
  - path: compose/docker-compose.seaweedfs.yml

services:
  create-user:
    build:
      context: .
      dockerfile: ./backend/services/useradm/Dockerfile
    image: ${MENDER_IMAGE_REGISTRY:-docker.io}/${MENDER_IMAGE_REPOSITORY:-mendersoftware}/useradm:${MENDER_IMAGE_TAG:-latest}
    restart: on-failure:20
    command: useradm create-user --username=${ADMIN_USER} --password=${ADMIN_PASSWORD}
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      USERADM_MONGO: mongodb://mongo
      USERADM_SERVER_PRIV_KEY_PATH: /etc/useradm/private.pem
    labels:
      traefik.enable: "true"
      traefik.http.services.useradm.loadBalancer.server.port: "8080"
      traefik.http.routers.useradm.middlewares: mgmtStack@file
      traefik.http.routers.useradm.rule: (Host(`${MENDER_HOSTNAME:-docker.mender.io}`)
        || Host(`localhost`) || Host(`traefik`)) &&
        PathRegexp(`/api/management/v[0-9a-z]+/useradm`)
      traefik.http.routers.useradm.service: useradm
      traefik.http.routers.userauth.middlewares: compression@file,sec-headers@file
      traefik.http.routers.userauth.rule: (Host(`${MENDER_HOSTNAME:-docker.mender.io}`)
        || Host(`localhost`) || Host(`traefik`)) &&
        (!PathRegexp(`/api/management/v[0-9a-z]+/useradm/auth/logout`) &&
        PathRegexp(`/api/management/v[0-9a-z]+/useradm/(auth|oauth2|oidc)`))
      traefik.http.routers.userauth.service: useradm
    networks:
      default:
        aliases:
          - mender-useradm
    volumes:
      - ./compose/config/mender.pem:/etc/useradm/private.pem
configs:
  client_json:
    content: |
      {
        "InventoryPollIntervalSeconds": 5,
        "RetryPollIntervalSeconds": 5,
        "ServerURL": "${SERVER_URL:-https://docker.mender.io}",
        "ServerCertificate": "/var/lib/mender/mender.crt",
        "UpdatePollIntervalSeconds": 5,
        "TenantToken": "${TENANT_TOKEN:-}"
      }
volumes:
  mongo: {}
